const EError = {
    //Entrada de datos
    USER_INVALID_DATA_ERROR: 101,
    USER_REGISTRATION_DATA_ERROR: 102,
    USER_MAIL_ERROR: 103,
    USER_GITHUB_DATA_ERROR: 104,
    CART_INVALID_CID_ERROR: 105,
    CART_INVALID_DATA_ERROR: 106,
    PRODUCT_INVALID_PID_ERROR: 107,
    PRODUCT_INVALID_DATA_ERROR: 108,
    //Database
    DATABASE_CONECTION_ERROR: 202,
    //Unkown
    UNKNOWED_ERROR: 999
}

export default EError